# Generated by Django 6.0.4 on 2026-04-12 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dog_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreedInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("breed", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "energy_level",
                    models.CharField(
                        choices=[
                            ("low", "Basso"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("very_high", "Molto Alto"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "social_level",
                    models.CharField(
                        choices=[
                            ("low", "Basso"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                            ("very_high", "Molto Alto"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "common_problems",
                    models.TextField(blank=True, help_text="Comma-separated list"),
                ),
                (
                    "traits",
                    models.TextField(blank=True, help_text="Caratteristiche tipiche"),
                ),
                (
                    "care_tips",
                    models.TextField(blank=True, help_text="Consigli di cura"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Razza",
                "verbose_name_plural": "Razze",
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("behavior", "Comportamento"),
                            ("health", "Salute"),
                            ("nutrition", "Alimentazione"),
                            ("training", "Educazione"),
                            ("lifestyle", "Vita Quotidiana"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Basso"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "common_breeds",
                    models.TextField(blank=True, help_text="Razze più colpite"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Problema",
                "verbose_name_plural": "Problemi",
            },
        ),
        migrations.CreateModel(
            name="Cause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "probability",
                    models.CharField(
                        choices=[
                            ("rare", "Rara"),
                            ("possible", "Possibile"),
                            ("common", "Comune"),
                            ("very_common", "Molto Comune"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="causes",
                        to="knowledge.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Causa",
                "verbose_name_plural": "Cause",
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solution_type",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("environment", "Ambiente"),
                            ("nutrition", "Alimentazione"),
                            ("health", "Salute"),
                            ("behavior", "Comportamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Facile"),
                            ("medium", "Media"),
                            ("hard", "Difficile"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "time_needed",
                    models.CharField(
                        blank=True, help_text="Es: 2 settimane", max_length=50
                    ),
                ),
                (
                    "success_rate",
                    models.CharField(
                        choices=[
                            ("low", "Basso"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("warnings", models.TextField(blank=True, help_text="Cose da evitare")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="knowledge.problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soluzione",
                "verbose_name_plural": "Soluzioni",
            },
        ),
        migrations.CreateModel(
            name="DogAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_description",
                    models.TextField(
                        help_text="Descrizione del problema data dall'utente"
                    ),
                ),
                ("ai_response", models.TextField(blank=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Da provare"),
                            ("improved", "Migliorato"),
                            ("no_change", "Nessun cambiamento"),
                            ("worse", "Peggiorato"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="dog_profile.dogprofile",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge.problem",
                    ),
                ),
                (
                    "suggested_solution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge.solution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analisi",
                "verbose_name_plural": "Analisi",
                "ordering": ["-created_at"],
            },
        ),
    ]
