# Generated by Django 6.0.4 on 2026-04-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeterinaryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titolo o Argomento Medico", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Contenuto integrale del documento, linee guida o posologia."
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        help_text="Parole chiave separate da virgole (es: cioccolato, teobromina)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Documento Veterinario",
                "verbose_name_plural": "Documenti Veterinari",
            },
        ),
    ]
