# Generated by Django 6.0.4 on 2026-04-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_veterinarydocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="cause",
            name="description_en",
            field=models.CharField(
                blank=True, help_text="English description", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="cause",
            name="notes_en",
            field=models.TextField(blank=True, help_text="English notes"),
        ),
        migrations.AddField(
            model_name="problem",
            name="description_en",
            field=models.TextField(blank=True, help_text="English description"),
        ),
        migrations.AddField(
            model_name="problem",
            name="title_en",
            field=models.CharField(
                blank=True, help_text="English title", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="description_en",
            field=models.TextField(blank=True, help_text="English description"),
        ),
        migrations.AddField(
            model_name="solution",
            name="time_needed_en",
            field=models.CharField(
                blank=True,
                help_text="English time needed (e.g. 2 weeks)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="title_en",
            field=models.CharField(
                blank=True, help_text="English title", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="warnings_en",
            field=models.TextField(blank=True, help_text="English warnings"),
        ),
    ]
