# Generated by Django 6.0.4 on 2026-04-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dog_profile",
            "0004_remove_healthevent_dog_dogprofile_activity_level_and_more",
        ),
        ("knowledge", "0004_populate_english_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifetimeMacroAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_snapshot",
                    models.JSONField(
                        help_text="I dati (medie, eventi) usati per generare questo report."
                    ),
                ),
                (
                    "ai_report_html",
                    models.TextField(help_text="Il referto generato in formato HTML."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="macro_analyses",
                        to="dog_profile.dogprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Macro-Analisi IA",
                "verbose_name_plural": "Macro-Analisi IA",
                "ordering": ["-created_at"],
            },
        ),
    ]
