# Generated by Django 6.0.4 on 2026-04-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DogProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("dog_name", models.CharField(max_length=100)),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Maschio"), ("female", "Femmina")],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profilo Cane",
                "verbose_name_plural": "Profili Cani",
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "sleep_hours",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("play_minutes", models.IntegerField(default=0)),
                ("walk_minutes", models.IntegerField(default=0)),
                ("food_grams", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="dog_profile.dogprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Giornaliero",
                "verbose_name_plural": "Registri Giornalieri",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HealthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("vaccine", "Vaccino"),
                            ("checkup", "Visita"),
                            ("medicine", "Medicina"),
                            ("illness", "Malattia"),
                            ("injury", "Infortunio"),
                            ("other", "Altro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("next_date", models.DateField(blank=True, null=True)),
                ("veterinarian", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="dog_profile.dogprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Salute",
                "verbose_name_plural": "Eventi Salute",
                "ordering": ["-date"],
            },
        ),
    ]
