# Generated by Django 6.0.4 on 2026-04-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dog_profile", "0002_dogprofile_owner"),
        ("knowledge", "0002_veterinarydocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeterinaryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_description",
                    models.TextField(help_text="Descrizione del problema"),
                ),
                (
                    "ai_summary",
                    models.TextField(blank=True, help_text="Riassunto AI generato"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bozza"),
                            ("ready", "Pronto"),
                            ("sent", "Inviato"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("vet_name", models.CharField(blank=True, max_length=200)),
                ("vet_email", models.EmailField(blank=True, max_length=254)),
                ("vet_phone", models.CharField(blank=True, max_length=50)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vet_requests",
                        to="knowledge.doganalysis",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vet_requests",
                        to="dog_profile.dogprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VeterinaryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Foto"), ("video", "Video")], max_length=10
                    ),
                ),
                ("file", models.FileField(upload_to="veterinary_requests/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("upload_order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="dog_profile.veterinaryrequest",
                    ),
                ),
            ],
        ),
    ]
