# Generated by Django 6.0.4 on 2026-04-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dog_profile", "0003_veterinaryrequest_veterinarymedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="dogprofile",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("low", "Basso – poco movimento"),
                    ("moderate", "Moderato – passeggiate normali"),
                    ("high", "Alto – molto attivo"),
                    ("very_high", "Molto alto – sportivo"),
                ],
                default="moderate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="current_medications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{\n            'name': 'Nome farmaco',\n            'dosage': '5mg',\n            'frequency': '2 volte/giorno',\n            'start_date': '2024-01-15',\n            'end_date': null,\n            'reason': 'Motivo prescrizione',\n            'vet_prescribed': true\n        }]",
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="diet_notes",
            field=models.TextField(
                blank=True, help_text="Intolleranze, allergie, cibi proibiti"
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="diet_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dry", "Crocchette"),
                    ("wet", "Umido"),
                    ("raw", "Crudo (BARF)"),
                    ("homemade", "Casalingo"),
                    ("mixed", "Misto"),
                ],
                default="dry",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="food_grams_per_day",
            field=models.IntegerField(
                blank=True, help_text="Grammi totali giornalieri", null=True
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="food_type",
            field=models.CharField(
                blank=True,
                help_text="Es: Croccantino Royal Canin Medium Adult",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="has_access_garden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="is_indoor",
            field=models.BooleanField(
                default=True, help_text="Vive prevalentemente in casa?"
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="is_neutered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="meals_per_day",
            field=models.IntegerField(default=2, help_text="Numero pasti giornalieri"),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="microchip",
            field=models.CharField(
                blank=True, help_text="Microchip number se presente", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="sleep_pattern",
            field=models.CharField(
                choices=[
                    ("normal", "Normale"),
                    ("excessive", "Eccessivo"),
                    ("restless", "Agitato/insonne"),
                    ("variable", "Variabile"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="socialization_level",
            field=models.CharField(
                choices=[
                    ("friendly", "Amichevole con tutti"),
                    ("selective", "Selettivo con alcuni"),
                    ("protective", "Protettivo/da guardia"),
                    ("shy", "Timido/riservato"),
                    ("reactive", "Reattivo/aggressivo"),
                ],
                default="friendly",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="supplements",
            field=models.TextField(
                blank=True,
                help_text="Integratori: nome + dosaggio (es: Glucosamina 500mg ×2)",
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="typical_walk_minutes",
            field=models.IntegerField(
                blank=True, help_text="Minuti medi di passeggiata/giorno", null=True
            ),
        ),
        migrations.AddField(
            model_name="dogprofile",
            name="weight_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{'date': '2024-01', 'weight': 28.5}, …]",
            ),
        ),
        migrations.CreateModel(
            name="MedicalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("visit", "Visita Veterinaria"),
                            ("exam", "Esame Diagnostico"),
                            ("vaccine", "Vaccinazione"),
                            ("surgery", "Intervento Chirurgico"),
                            ("therapy_start", "Inizio Terapia"),
                            ("therapy_end", "Fine Terapia"),
                            ("emergency", "Pronto Soccorso"),
                            ("followup", "Controllo"),
                            ("other", "Altro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Titolo breve: es. 'Vaccino annuale'",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrizione libera (compatibilità)"
                    ),
                ),
                ("vet_clinic", models.CharField(blank=True, max_length=200)),
                ("vet_name", models.CharField(blank=True, max_length=200)),
                (
                    "diagnosis",
                    models.TextField(blank=True, help_text="Diagnosi del veterinario"),
                ),
                (
                    "prescribed_medications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Farmaci prescritti: [{name, dosage, duration, notes}]",
                    ),
                ),
                (
                    "prescribed_tests",
                    models.TextField(blank=True, help_text="Esami prescritti"),
                ),
                (
                    "treatment_description",
                    models.TextField(blank=True, help_text="Terapia applicata"),
                ),
                ("outcome", models.TextField(blank=True, help_text="Risultato finale")),
                ("next_event_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Note aggiuntive")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_events",
                        to="dog_profile.dogprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Medico",
                "verbose_name_plural": "Eventi Medici",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Giornaliera"),
                            ("symptom", "Sintomo Osservato"),
                            ("behavior", "Comportamento Anomalo"),
                            ("diet", "Variazione Alimentare"),
                            ("medication", "Somministrazione Farmaco"),
                            ("vital_signs", "Segni Vitali (temperatura, frequenza…)"),
                            ("note", "Nota Libera"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("1", "Lieve – monitorare"),
                            ("2", "Moderato – attenzione"),
                            ("3", "Severo – consultare"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Durata (ore) se sintomo/comportamento",
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        blank=True,
                        help_text="Frequenza episodi nella giornata",
                        null=True,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Temperatura °C",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, help_text="Battiti/minuto", null=True
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, help_text="Respiri/minuto", null=True
                    ),
                ),
                ("description", models.TextField(help_text="Descrizione dettagliata")),
                (
                    "sleep_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Ore sonno (24h)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "play_minutes",
                    models.IntegerField(
                        blank=True, help_text="Minuti di gioco/attività", null=True
                    ),
                ),
                (
                    "walk_minutes",
                    models.IntegerField(
                        blank=True, help_text="Minuti passeggiata", null=True
                    ),
                ),
                (
                    "food_grams",
                    models.IntegerField(
                        blank=True, help_text="Grammi cibo totale", null=True
                    ),
                ),
                (
                    "ai_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags auto-generati dal sistema AI",
                    ),
                ),
                (
                    "ai_summary_suggestion",
                    models.TextField(
                        blank=True, help_text="Suggerimento AI per pattern recognition"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to="dog_profile.dogprofile",
                    ),
                ),
                (
                    "media",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Foto/video associati a questa osservazione",
                        related_name="health_logs",
                        to="dog_profile.veterinarymedia",
                    ),
                ),
                (
                    "related_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Evento medico collegato (se applicabile)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_logs",
                        to="dog_profile.medicalevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Sanitario",
                "verbose_name_plural": "Log Sanitari",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="healthlog",
            index=models.Index(
                fields=["dog", "date"], name="dog_profile_dog_id_8372dd_idx"
            ),
        ),
        migrations.DeleteModel(
            name="DailyLog",
        ),
        migrations.DeleteModel(
            name="HealthEvent",
        ),
    ]
