# Generated by Django 6.0.4 on 2026-04-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_add_unsubscribe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="followup_step",
            field=models.IntegerField(
                default=0, help_text="Current step in the onboarding sequence (1-3)"
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="last_email_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="welcome_sent",
            field=models.BooleanField(default=False),
        ),
    ]
