# Generated by Django 6.0.4 on 2026-04-26 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "dog_profile",
            "0004_remove_healthevent_dog_dogprofile_activity_level_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(verbose_name="Descrizione")),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronzo"),
                            ("silver", "Argento"),
                            ("gold", "Oro"),
                            ("platinum", "Platino"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icona"),
                ),
                (
                    "requirement_type",
                    models.CharField(max_length=50, verbose_name="Tipo requisito"),
                ),
                (
                    "requirement_value",
                    models.IntegerField(verbose_name="Valore requisito"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Attivo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badge",
                "ordering": ["badge_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji o icona (es: 🍖, 💊, 🎓)",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#059669",
                        help_text="Colore esadecimale (es: #059669)",
                        max_length=7,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Ordine di visualizzazione"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoria Community",
                "verbose_name_plural": "Categorie Community",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserReputation",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="reputation",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utente",
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="Punti")),
                ("level", models.IntegerField(default=1, verbose_name="Livello")),
                (
                    "discussions_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Discussioni create"
                    ),
                ),
                (
                    "posts_created",
                    models.PositiveIntegerField(default=0, verbose_name="Post creati"),
                ),
                (
                    "solutions_provided",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Soluzioni provide"
                    ),
                ),
                (
                    "helpful_votes_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Voti utili ricevuti"
                    ),
                ),
                (
                    "likes_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Mi piace ricevuti"
                    ),
                ),
                (
                    "moderation_strikes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Strike moderazione"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultimo aggiornamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reputazione Utente",
                "verbose_name_plural": "Reputazioni Utenti",
                "ordering": ["-points"],
            },
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titolo")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField(verbose_name="Contenuto")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aperta"),
                            ("closed", "Chiusa"),
                            ("archived", "Archiviata"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normale"),
                            ("pinned", "Fissa"),
                            ("important", "Importante"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Priorità",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Approved"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Visualizzazioni"
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="Mi piace"),
                ),
                (
                    "reply_count",
                    models.PositiveIntegerField(default=0, verbose_name="Risposte"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="Ultima attività"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creata il"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autore",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discussions",
                        to="community.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discussions",
                        to="dog_profile.dogprofile",
                        verbose_name="Cane collegato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discussione",
                "verbose_name_plural": "Discussioni",
                "ordering": ["-priority", "-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenuto")),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Modificato"),
                ),
                (
                    "edit_reason",
                    models.TextField(blank=True, verbose_name="Motivo modifica"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Modificato il"
                    ),
                ),
                (
                    "is_solution",
                    models.BooleanField(default=False, verbose_name="Soluzione"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="Mi piace"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aggiornato il"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autore",
                    ),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="community.discussion",
                        verbose_name="Discussione",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="community.post",
                        verbose_name="Post genitore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Post",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reply", "Nuova risposta"),
                            ("mention", "Menzione"),
                            ("like", "Mi piace"),
                            ("solution", "Soluzione accettata"),
                            ("badge", "Badge ottenuto"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("message", models.TextField(verbose_name="Messaggio")),
                ("is_read", models.BooleanField(default=False, verbose_name="Letta")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creata il"),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.discussion",
                        verbose_name="Discussione",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatario",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mittente",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifica",
                "verbose_name_plural": "Notifiche",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("discussion", "Discussione"), ("post", "Post")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussion_likes",
                        to="community.discussion",
                        verbose_name="Discussione",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utente",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="community.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mi piace",
                "verbose_name_plural": "Mi piace",
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Guadagnato il"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="community.badge",
                        verbose_name="Badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge Utente",
                "verbose_name_plural": "Badge Utenti",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("up", "Su"), ("down", "Giù")],
                        max_length=4,
                        verbose_name="Tipo voto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creato il"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_votes",
                        to="community.post",
                        verbose_name="Post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto",
                "verbose_name_plural": "Voti",
            },
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["category", "status"], name="community_d_categor_77bb10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["author", "created_at"], name="community_d_author__aa8dc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discussion",
            index=models.Index(
                fields=["-last_activity"], name="community_d_last_ac_052314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["discussion", "created_at"],
                name="community_p_discuss_7e3965_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "created_at"], name="community_p_author__54f6fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="community_n_recipie_def321_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["user", "content_type"], name="community_l_user_id_76d246_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["discussion"], name="community_l_discuss_3fb027_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(fields=["post"], name="community_l_post_id_4ab6ad_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "content_type", "discussion", "post")},
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge")},
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["post", "vote_type"], name="community_v_post_id_2563c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "post")},
        ),
    ]
