# Generated by Django 6.0.4 on 2026-04-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="importance",
            field=models.CharField(
                choices=[("high", "Alta"), ("medium", "Media"), ("low", "Basica")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="length",
            field=models.CharField(
                choices=[("short", "Breve"), ("medium", "Medio"), ("long", "Lungo")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="source",
            field=models.CharField(
                choices=[
                    ("ai", "AI Generato"),
                    ("manual", "Manuale"),
                    ("news", "Notizia"),
                    ("translated", "Tradotto"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
