# Generated by Django 6.0.4 on 2026-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_importance_blogpost_length_blogpost_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Descrizione ottimizzata per i motori di ricerca (max 160 caratteri).",
                max_length=160,
            ),
        ),
    ]
