# Generated by Django 6.0.4 on 2026-04-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_meta_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="content_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
