# Generated by Django 6.0.4 on 2026-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpost_content_en_blogpost_title_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
