#!/bin/bash
# Test Suite Completa - Vivere con il Cane
# Esegue tutti i test con diverse configurazioni e genera report dettagliati

set -e

echo "🧪 Vivere con il Cane - Full Test Suite"
echo "========================================"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_test() { echo -e "${BLUE}[TEST]${NC} $1"; }

# Timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="test_full_${TIMESTAMP}.log"
REPORT_FILE="TEST_REPORT_${TIMESTAMP}.md"

# Initialize log
echo "Test Run: $(date)" > "$LOG_FILE"
echo "========================================" >> "$LOG_FILE"

# Function to run test and log
run_test() {
    local name="$1"
    local cmd="$2"
    echo ""
    log_test "Running: $name"
    echo "--------------------------------------------------" >> "$LOG_FILE"
    echo "Test: $name" >> "$LOG_FILE"
    echo "Command: $cmd" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"

    if eval "$cmd" >> "$LOG_FILE" 2>&1; then
        log_info "✓ $name PASSED"
        echo "Result: PASSED ✓" >> "$LOG_FILE"
        return 0
    else
        log_error "✗ $name FAILED"
        echo "Result: FAILED ✗" >> "$LOG_FILE"
        return 1
    fi
}

# Check environment
log_info "Checking environment..."
if [ -z "${VIRTUAL_ENV}" ]; then
    log_warn "Virtual environment not activated. Consider: source venv/bin/activate"
fi

# Ensure .env exists
if [ ! -f ".env" ]; then
    log_warn ".env file missing. Copy from .env.example and configure."
fi

# Test 1: Fast checks (syntax, imports)
run_test "Syntax Check (Python)" "python -m py_compile $(find . -name '*.py' -not -path './venv/*' -not -path './.git/*')"

# Test 2: Django checks
run_test "Django System Check" "python manage.py check"

# Test 3: Run all tests with pytest (fast)
run_test "All Tests (pytest -x)" "python -m pytest --ds=config.settings -x -v"

# Test 4: With coverage
run_test "Coverage Report" "python -m pytest --ds=config.settings --cov=. --cov-report=term --cov-report=html"

# Test 5: Specific apps (critical ones)
run_test "Blog App Tests" "python manage.py test blog --debug-mode -v 2"
run_test "Knowledge App Tests" "python manage.py test knowledge --debug-mode -v 2"
run_test "Dog Profile Tests" "python manage.py test dog_profile --debug-mode -v 2"
run_test "Canine Tools Tests" "python manage.py test canine_tools --debug-mode -v 2"

# Test 6: Community (if stable)
run_test "Community App Tests" "python manage.py test community --debug-mode -v 2" || true

# Test 7: Integration - AI client (mock)
run_test "AI Client Integration" "python -c \"from canine_tools.services.ai_client import test_groq; test_groq()\" 2>/dev/null || echo 'Groq API not configured (expected)'"

# Test 8: PDF generation
run_test "PDF Generation Test" "python manage.py shell -c \"from dog_profile.views import test_pdf; test_pdf()\" 2>/dev/null || echo 'PDF test skipped'"

# Test 9: Static files collection
run_test "Static Files Collection" "python manage.py collectstatic --noinput --dry-run"

# Test 10: URL resolution
run_test "URL Resolution Check" "python manage.py show_urls" 2>/dev/null || echo "show_urls not available (django-extensions not installed)"

# Summary
echo ""
echo "========================================"
log_info "Test suite complete!"
echo "========================================"

# Count results
PASSED=$(grep -c "Result: PASSED" "$LOG_FILE" 2>/dev/null || echo "0")
FAILED=$(grep -c "Result: FAILED" "$LOG_FILE" 2>/dev/null || echo "0")

echo "Passed: $PASSED"
echo "Failed: $FAILED"
echo "Log saved to: $LOG_FILE"

# Generate markdown report
cat > "$REPORT_FILE" <<EOF
# Test Report - Vivere con il Cane

**Date:** $(date)
**Python Version:** $(python --version 2>&1)
**Django Version:** $(python -c "import django; print(django.VERSION)" 2>/dev/null || echo "Unknown")
**Platform:** $(uname -a 2>/dev/null || echo "Windows")

## Summary

| Metric | Value |
|--------|-------|
| Total Tests Run | $((PASSED + FAILED)) |
| Passed | $PASSED ✅ |
| Failed | $FAILED ❌ |
| Pass Rate | $(awk "BEGIN {printf \"%.1f%%\", $PASSED*100.0/($PASSED+$FAILED)}") |

## Test Details

$(grep "^Test:" "$LOG_FILE" | while read line; do
    test_name=$(echo "$line" | cut -d: -f2-)
    result=$(grep -A1 "Test: $test_name" "$LOG_FILE" | grep "Result:")
    echo "- $test_name: $result"
done)

## Environment

- **DEBUG:** ${DEBUG:-not set}
- **DATABASE_URL:** ${DATABASE_URL:-sqlite (default)}
- **GROQ_API_KEY:** ${GROQ_API_KEY:+[SET]:-[NOT SET]}

## Issues Found

$(if [ "$FAILED" -gt 0 ]; then
    echo "Check the log file for details: $LOG_FILE"
else
    echo "None - all tests passed!"
fi)

---

*Generated by scripts/test_all.sh*
EOF

log_info "Report saved to: $REPORT_FILE"

# Suggest next steps
if [ "$FAILED" -eq 0 ]; then
    log_info "🎉 All tests passed! Ready to commit/deploy."
else
    log_error "⚠️  Some tests failed. Review $LOG_FILE"
fi

echo ""
log_info "Coverage HTML report: htmlcov/index.html"
