# Generated by Django 6.0.4 on 2026-04-25 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "dog_profile",
            "0004_remove_healthevent_dog_dogprofile_activity_level_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeartSoundRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="heart_recordings/%Y/%m/")),
                (
                    "duration_seconds",
                    models.FloatField(help_text="Durata registrazione in secondi"),
                ),
                (
                    "estimated_bpm",
                    models.IntegerField(help_text="Battiti per minuto stimati"),
                ),
                (
                    "beat_count",
                    models.IntegerField(help_text="Numero totale battiti rilevati"),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Confidenza dell'analisi (0-1)"),
                ),
                (
                    "peak_times",
                    models.JSONField(
                        help_text="Lista timestamp (secondi) dei picchi cardiaci"
                    ),
                ),
                (
                    "amplitudes",
                    models.JSONField(
                        help_text="Lista ampiezze normalizzate dei picchi"
                    ),
                ),
                (
                    "sample_rate",
                    models.IntegerField(default=44100, help_text="Sample rate audio"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Note: a riposo, dopo attività, ecc."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heart_recordings",
                        to="dog_profile.dogprofile",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heart_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
