# Generated by Django 6.0.4 on 2026-04-25 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canine_tools", "0001_initial"),
        (
            "dog_profile",
            "0004_remove_healthevent_dog_dogprofile_activity_level_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="heartsoundrecording",
            name="estimated_bpm",
            field=models.IntegerField(help_text="Battuti per minuto stimati"),
        ),
        migrations.CreateModel(
            name="HealthConnectToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(help_text="Token di accesso OAuth")),
                (
                    "refresh_token",
                    models.TextField(help_text="Token di refresh (per rinnovo)"),
                ),
                ("token_expiry", models.DateTimeField(help_text="Scadenza del token")),
                ("scopes", models.TextField(help_text="Scope autorizzati (JSON list)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_connect_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthDataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("steps", "Passi"),
                            ("heart_rate", "Frequenza Cardiaca"),
                            ("distance", "Distanza"),
                            ("calories", "Calorie"),
                            ("weight", "Peso"),
                            ("sleep", "Sonno"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(help_text="Inizio misurazione")),
                ("end_time", models.DateTimeField(help_text="Fine misurazione")),
                ("value", models.FloatField(help_text="Valore misurato")),
                (
                    "unit",
                    models.CharField(
                        help_text="Unità di misura (es. 'steps', 'bpm', 'm')",
                        max_length=20,
                    ),
                ),
                (
                    "data_source_name",
                    models.CharField(
                        blank=True, help_text="Fonte dati Google", max_length=200
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        default=dict, help_text="JSON completo della risposta API"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_data_points",
                        to="dog_profile.dogprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["dog", "source_type", "-start_time"],
                        name="canine_tool_dog_id_d0c43b_idx",
                    )
                ],
                "unique_together": {("dog", "source_type", "start_time")},
            },
        ),
    ]
