# Generated by Django 6.0.4 on 2026-04-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canine_tools", "0002_alter_heartsoundrecording_estimated_bpm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartsoundrecording",
            name="recording_context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rest", "A riposo"),
                    ("after_activity", "Dopo attività"),
                    ("before_meal", "Prima del pasto"),
                    ("after_meal", "Dopo il pasto"),
                    ("during_sleep", "Durante il sonno"),
                    ("stress", "Situazione di stress"),
                ],
                help_text="Contesto in cui è stata effettuata la registrazione",
                max_length=20,
            ),
        ),
    ]
